BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Valores";
CREATE TABLE IF NOT EXISTS "Valores" (
	"id"	INTEGER,
	"Nombre"	TEXT NOT NULL,
	"Valor"	TEXT NOT NULL,
	"fecha_hora"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
